# kaeland = Student.create(name:"Kaeland")
# kwam = Student.create(name:"Kwam")
# will = Student.create(name:"Will")
# cory = Student.create(name:"Cory")
# andy = Student.create(name:"Andy")
# paris = Student.create(name:"Paris")
# ed = Student.create(name:"Ed")
# blair = Student.create(name:"Blair")

rob = Instructor.create(name:"robby", is_generous: 1)
emily = Instructor.create(name:"emily", is_generous: 1)
brit = Instructor.create(name:"brit", is_generous: 1)
garry = Instructor.create(name:"garry", is_generous: 1)
ronnie = Instructor.create(name:"ronny", is_generous: 1)
tez = Instructor.create(name:"tez", is_generous: 1)

# meeting_1 = Meeting.create(instructor_id: rob.id, student_id: kwam.id, topic: nil, question: nil, answer: nil)
# meeting_2 = Meeting.create(instructor_id: emily.id, student_id: kwam.id, topic: nil, question: nil, answer: nil)
# meeting_3 = Meeting.create(instructor_id: emily.id, student_id: kwam.id, topic: nil, question: nil, answer: nil)

